Laboratorium 3 - App/Models/Travel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_3___App.Models
{
    public class Travel
    {
        [HiddenInput]
        public int Id { get; set; }

        [Required(ErrorMessage = "Musisz podać nazwe!")]
        [StringLength(maximumLength: 50, ErrorMessage = "Za długa nazwa! Maksymalnie 50 znaków.")]
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        [Required(ErrorMessage = "Musisz podać miejsce początkowe wycieczki!")]
        [StringLength(maximumLength: 50, ErrorMessage = "Za długa nazwa! Maksymalnie 50 znaków.")]
        public string StartPlace { get; set; }

        [Required(ErrorMessage = "Musisz podać miejsce początkowe wycieczki!")]
        [StringLength(maximumLength: 50, ErrorMessage = "Za długa nazwa! Maksymalnie 50 znaków.")]
        public string EndPlace { get; set; }
        public int NumbParticipants { get; set; }
        [Required(ErrorMessage = "Musisz podać nazwe!")]
        [StringLength(maximumLength: 50, ErrorMessage = "Za długa nazwa! Maksymalnie 50 znaków.")]
        public string Guide { get; set; }

        public int? TravelAgencyId { get; set; }
        [ValidateNever]
        public List<SelectListItem> TravelAgenciesList { get; set; }

    }
}

Laboratorium 3 - App/Controllers/TravelController.cs
using Laboratorium_3___App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Laboratorium_3___App.Controllers
{
    public class TravelController : Controller
    {
        private readonly ITravelService _travelService;

        public TravelController(ITravelService travelService)
        {
            _travelService = travelService;
        }

        //static Dictionary<int, Travel> _travels = new Dictionary<int, Travel>();
        //static int id = 1;
        [AllowAnonymous]
        public IActionResult Index()
        {
            var travels = _travelService.FindAll();
            var travelDictionary = travels.ToDictionary(c => c.Id);
            return View(travelDictionary);
        }
        private List<SelectListItem> CreateTravelAngienciesList()
        {
            return _travelService.FindAllTravelAgency()
                .Select(e => new SelectListItem()
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }).ToList();
        }

        [HttpGet]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult Create() 
        {
            List<SelectListItem> travelAgencies = _travelService.FindAllTravelAgency()
                .Select(e => new SelectListItem()
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }).ToList();
            return View(new Travel() { TravelAgenciesList = travelAgencies });
        }
        [HttpPost]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult Create(Travel model) 
        {
            if (ModelState.IsValid)
            {
                _travelService.add(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult CreateApi()
        {
            return View();
            /*
            List<SelectListItem> organizations = _contactService.FindAllOrganization()
                .Select(e => new SelectListItem()
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }).ToList();
            return View(new Contact() { OrganizationsList = organizations });*/
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult CreateApi(Travel model)
        {
            if (ModelState.IsValid)
            {
                _travelService.add(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Update(int id)
        {
            return View(_travelService.FindByID(id));
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Update(Travel model)
        {
            if (ModelState.IsValid)
            {
                _travelService.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            return View(_travelService.FindByID(id));
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(Travel model)
        {
            _travelService.RemoveByID(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            return View(_travelService.FindByID(id));
        }
    }
}

Laboratorium 3 - App/Views/Travel/Create.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Dodaj nową wycieczkę</h1>
<form asp-controller="Travel" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name">Nazwa Wycieczki</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Data Rozpoczęcia</label>
        <input class="form-control" asp-for="StartDate" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">Data Zakończenia</label>
        <input class="form-control" asp-for="EndDate" />
        <span class="text-danger" asp-validation-for="EndDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartPlace">Miejsce Rozpoczęcia</label>
        <input class="form-control" asp-for="StartPlace" />
        <span class="text-danger" asp-validation-for="StartPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndPlace">Miejsce Zakończenia</label>
        <input class="form-control" asp-for="EndPlace" />
        <span class="text-danger" asp-validation-for="EndPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="NumbParticipants">Liczba uczestników</label>
        <input class="form-control" asp-for="NumbParticipants" />
        <span class="text-danger" asp-validation-for="NumbParticipants"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Guide">Przewodnik</label>
        <input class="form-control" asp-for="Guide" />
        <span class="text-danger" asp-validation-for="Guide"></span>
    </div>
    <div class="form-group">
        <label asp-for="TravelAgencyId">Organizacja</label>
        <select class="form-control" asp-for="TravelAgencyId" asp-items="@Model.TravelAgenciesList"></select>
    </div>
    <div class="mb-3">
        <button class="btn btn-primary" type="submit"> Utwórz</button>
    </div>
</form>

Laboratorium 3 - App/Views/Travel/CreateApi.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Dodaj nową wycieczkę</h1>
<form asp-controller="Travel" asp-action="CreateApi" method="post">
    <div class="mb-3">
        <label asp-for="Name">Nazwa Wycieczki</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Data Rozpoczęcia</label>
        <input class="form-control" asp-for="StartDate" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">Data Zakończenia</label>
        <input class="form-control" asp-for="EndDate" />
        <span class="text-danger" asp-validation-for="EndDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartPlace">Miejsce Rozpoczęcia</label>
        <input class="form-control" asp-for="StartPlace" />
        <span class="text-danger" asp-validation-for="StartPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndPlace">Miejsce Zakończenia</label>
        <input class="form-control" asp-for="EndPlace" />
        <span class="text-danger" asp-validation-for="EndPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="NumbParticipants">Liczba uczestników</label>
        <input class="form-control" asp-for="NumbParticipants" />
        <span class="text-danger" asp-validation-for="NumbParticipants"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Guide">Przewodnik</label>
        <input class="form-control" asp-for="Guide" />
        <span class="text-danger" asp-validation-for="Guide"></span>
    </div>
    <div class="form-group">
        <label asp-for="TravelAgencyId">Biuro Podróży</label>
        <input class="form-control" type="text" id="filter" />
        <select class="form-control" asp-for="TravelAgencyId"></select>
    </div>
    <br />
    <div class="mb-3">
        <button class="btn btn-primary" type="submit"> Utwórz</button>
    </div>
</form>

@section Scripts{
    <script>
        const select = document.getElementById('TravelAgencyId');
        const filter = document.getElementById('filter');
        filter.onchange = function(){
            select.innerHTML = "";
            fetch(`/api/TravelAgencies?q=${filter.value}`)
            .then(response => response.json())
                .then(TravelAgencies => {
                    for (let org of TravelAgencies) {
                    const option = document.createElement('option');
                    option.setAttribute('value', org.id);
                    option.innerText = org.name;
                    select.appendChild(option);
                }
            });
        }
    </script>
}

Laboratorium 3 - App/Views/Travel/Delete.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Czy na pewno chcesz usunąć poniższą wycieczke</h1>
<p>Nazwa Wycieczki</p>
<h4>@Model.Name</h4>
<p>Przewodnik</p>
<h4>@Model.Guide</h4>
<form asp-action="Delete">
    <input asp-for="Id" />
    <button class="btn btn-danger" type="submit">Tak</button>
</form>

Laboratorium 3 - App/Views/Travel/Details.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Szczegóły wycieczki</h1>
<p>Nazwa Wycieczki</p>
<h4>@Model.Name</h4>
<p>Data Rozpoczęcia</p>
<h4>@Model.StartDate</h4>
<p>Data Zakończenia</p>
<h4>@Model.EndDate</h4>
<p>Miejsce Początkowe</p>
<h4>@Model.StartPlace</h4>
<p>Miejsce Zakończenia</p>
<h4>@Model.EndPlace</h4>
<p>Liczba Uczestników</p>
<h4>@Model.NumbParticipants</h4>
<p>Przewodnik</p>
<h4>@Model.Guide</h4>


<form asp-action="Index">
    <input asp-for="Id" />
    <button class="btn btn-primary" type="submit">WRÓĆ</button>
</form>

Laboratorium 3 - App/Views/Travel/Index.cshtml
@model Dictionary<int, Travel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Lista wycieczek</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Travel" asp-action="Create">Dodaj Wycieczke</a>
<a class="btn btn-primary" asp-area="" asp-controller="Travel" asp-action="CreateApi">Dodaj Wycieczke API</a>
@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th class="text-white">
                    Nazwa Wycieczki
                </th>
                <th class="text-white">
                    Przewodnik
                </th>
                <th class="text-white">
                    Akcje
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="@(item.Value.Name.EndsWith("a")? "text-primary":"text-secondary text-white")">
                        @item.Value.Name
                    </td>
                    <td class="text-white">
                        @item.Value.Guide
                    </td>
                    <td class="text-white">
                        <a class="btn btn-outline-success" asp-action="Update" asp-route-id=@item.Key>Edycja</a>
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id=@item.Key>Szczegóły</a>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id=@item.Key>Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Laboratorium 3 - App/Views/Travel/Update.cshtml
@model Travel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Edytuj wycieczke</h1>
<form asp-controller="Travel" asp-action="Update" method="post">
    <input asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Name">Nazwa Wycieczki</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartDate">Data Rozpoczęcia</label>
        <input class="form-control" asp-for="StartDate" />
        <span class="text-danger" asp-validation-for="StartDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndDate">Data Zakończenia</label>
        <input class="form-control" asp-for="EndDate" />
        <span class="text-danger" asp-validation-for="EndDate"></span>
    </div>
    <div class="mb-3">
        <label asp-for="StartPlace">Miejsce Rozpoczęcia</label>
        <input class="form-control" asp-for="StartPlace" />
        <span class="text-danger" asp-validation-for="StartPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="EndPlace">Miejsce Zakończenia</label>
        <input class="form-control" asp-for="EndPlace" />
        <span class="text-danger" asp-validation-for="EndPlace"></span>
    </div>
    <div class="mb-3">
        <label asp-for="NumbParticipants">Liczba uczestników</label>
        <input class="form-control" asp-for="NumbParticipants" />
        <span class="text-danger" asp-validation-for="NumbParticipants"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Guide">Przewodnik</label>
        <input class="form-control" asp-for="Guide" />
        <span class="text-danger" asp-validation-for="Guide"></span>
    </div>
    <div class="mb-3">
        <button class="btn btn-primary" type="submit"> Zapisz zmiany</button>
    </div>
</form>