Laboratorium 3 - App/Models/Contact.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace Laboratorium_3___App.Models
{
 
    static public class EnumExtension
    {
        static public string GetDisplayName(this Enum e)
        {
            return
                e.GetType()
                .GetMember(e.ToString())
                .First()
                .GetCustomAttribute<DisplayAttribute>().GetName();
        }
    }
    /*public enum Priority
    {
        [Display(Name = "Niski")] Low = 1,
        [Display(Name = "Normalny")] Normal = 2,
        [Display(Name = "Wysoki")] High = 3,
        [Display(Name = "Pilny")] Urgent = 4
    }*/
    public class Contact
    {
        
        // Usuń atrybut HiddenInput
        [Display(Name = "Priorytet")]
        public Priority Priority { get; set; }

        // Pozostałe właściwości
        [HiddenInput]
        public int Id { get; set; }
        [Display(Name = "Imię")]
        [Required(ErrorMessage = "Musisz podać imię!")]
        [StringLength(maximumLength: 50, ErrorMessage = "Imię zbyt długie maksymalnie 50 znaków")]
        public string Name { get; set; }
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Musissz podać poprawny email! (Brak znaku: @)")]
        public string Email { get; set; }
        [Display(Name = "Numer Telefonu")]
        [Phone(ErrorMessage = "Numer telefonu powinien zawierać cyfry")]
        public string Phone { get; set; }
        [Display(Name = "Data Urodzin")]
        [DataType(DataType.Date)]
        public DateTime? Birth { get; set; }
        [Display(Name = "Priorytet")]
        public int? OrganizationId { get; set; }
        [ValidateNever]
        public List<SelectListItem> OrganizationsList { get; set; }
        

        [HiddenInput]
        public DateTime Created { get; set; }
    }
}

Laboratorium 3 - App/Controllers/ContactController.cs
using Laboratorium_3___App.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Laboratorium_3___App.Controllers
{
    // dotnet tool install --global dotnet-ef
    // dotnet ef migrations add init
    // dotnet ef database update

    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        public ContactController(IContactService contactService)
        {
            _contactService = contactService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            /*
            var contacts = _contactService.FindAll();
            // Zamień listę na słownik, jeśli to jest wymagane przez Twój widok
            var contactDictionary = contacts.ToDictionary(c => c.Id);
            //return View(contactDictionary);
            return View(contactDictionary.Values.ToList());*/
            var contacts = _contactService.FindAll();
            // Zamień listę na słownik, jeśli to jest wymagane przez Twój widok
            var contactDictionary = contacts.ToDictionary(c => c.Id);
            return View(contactDictionary);

        }

        public IActionResult PagedIndex(int page = 1, int size = 5)
        {
            if (size < 2)
            {
                return BadRequest();
            }
            return View(_contactService.FindPage(page, size));
        }

        private List<SelectListItem> CreateOrganizationsList()
        {
            return _contactService.FindAllOrganization()
                .Select(e => new SelectListItem()
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }).ToList();
        }

        [HttpGet]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult Create()
        {
            List<SelectListItem> organizations = _contactService.FindAllOrganization()
                .Select(e => new SelectListItem()
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }).ToList();
            return View(new Contact() { OrganizationsList = organizations });
        }

        [HttpPost]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult Create(Contact model)
        {
            if (ModelState.IsValid)
            {
                model.Priority = model.Priority;
                _contactService.add(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult CreateApi()
        {
            return View();
            /*
            List<SelectListItem> organizations = _contactService.FindAllOrganization()
                .Select(e => new SelectListItem()
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }).ToList();
            return View(new Contact() { OrganizationsList = organizations });*/
        }

        [HttpPost]
        [Authorize(Roles = "visitor,admin")]
        public IActionResult CreateApi(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.add(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Update(int id)
        {
            return View(_contactService.FindByID(id));
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Update(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contactService.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            return View(_contactService.FindByID(id));
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(Contact model)
        {
            _contactService.RemoveByID(model.Id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Details(int id)
        {
            return View(_contactService.FindByID(id));
        }

    }
}

Laboratorium 3 - App/Views/Contact/Create.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Dodaj nowy kontakt</h1>
<form asp-controller="Contact" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone"></label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth"></label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Priority"></label>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
        <span class="text-danger" asp-validation-for="Priority"></span>
    </div>
    <div class="form-group">
        <label asp-for="OrganizationId">Organizacja</label>
        <select class="form-control" asp-for="OrganizationId" asp-items="@Model.OrganizationsList"></select>
    </div>
    <br />

    <div class="mb-3">
        <button class="btn btn-primary" type="submit"> Utwórz</button>
    </div>
</form>

Laboratorium 3 - App/Views/Contact/CreateApi.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Dodaj nowy kontakt</h1>
<form asp-controller="Contact" asp-action="CreateApi" method="post">
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email"></label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone"></label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth"></label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Priority"></label>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
        <span class="text-danger" asp-validation-for="Priority"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="OrganizationId">Organizacja</label>
        <input class ="form-control" type="text" id="filter" />
        <select class="form-control" asp-for="OrganizationId"></select>
        <span class="text-danger" asp-validation-for="Priority"></span>
    </div>
    <br />

    <div class="mb-3">
        <button class="btn btn-primary" type="submit"> Utwórz</button>
    </div>
</form>

@section Scripts{
    <script>
        const select = document.getElementById('OrganizationId');
        const filter = document.getElementById('filter');
        filter.onchange = function(){
            select.innerHTML = "";
            fetch(`/api/organizations?q=${filter.value}`)
            .then(response => response.json())
            .then(organizations => {
                for(let org of organizations){
                    const option = document.createElement('option');
                    option.setAttribute('value', org.id);
                    option.innerText = org.name;
                    select.appendChild(option);
                }
            });
        }
    </script>
}

Laboratorium 3 - App/Views/Contact/Delete.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Czy na pewno chcesz usunąć poniższy kontakt</h1>
<p>imię</p>
<h4>@Model.Name</h4>
<p>email</p>
<h4>@Model.Email</h4>
<form asp-action="Delete">
    <input asp-for="Id" />
    <button class="btn btn-danger" type="submit">Tak</button>
</form>

Laboratorium 3 - App/Views/Contact/Details.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Szczegóły kontaktu</h1>
<p>imię</p>
<h4>@Model.Name</h4>
<p>email</p>
<h4>@Model.Email</h4>
<p>Telefon</p>
<h4>@Model.Phone</h4>
<p>Data urodzenia</p>
<h4>@Model.Birth</h4>
<p>Priorytet</p>
<h4>@Model.Priority</h4>
<p>Czas utworzenia</p>
<h4>@Model.Created</h4>


<form asp-action="Index">
    <input asp-for="Id" />
    <button class="btn btn-primary" type="submit">WRÓĆ</button>
</form>

Laboratorium 3 - App/Views/Contact/Index.cshtml
@model Dictionary<int, Contact>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Lista kontaktów</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Contact" asp-action="Create">Dodaj Kontakt</a>
<a class="btn btn-primary" asp-area="" asp-controller="Contact" asp-action="CreateApi">Dodaj Kontakt API</a>
@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th class="text-white">
                    @Html.DisplayNameFor(model => model[0].Name)
                </th>
                <th class="text-white">
                    @Html.DisplayNameFor(model => model[0].Email)
                </th>
                <th class="text-white">
                    @Html.DisplayNameFor(model => model[0].Priority)
                </th >
                <th class="text-white">
                    Akcje
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in @Model)
            {
                <tr>
                    <td class="@(item.Value.Name.EndsWith("a")? "text-primary":"text-secondary text-white")">
                        @item.Value.Name
                    </td>
                    <td class="text-white">
                        @item.Value.Email
                    </td>
                    <td class="text-white">
                        @item.Value.Priority
                    </td>
                    <td class="text-white">
                        <a class="btn btn-outline-success" asp-action="Update" asp-route-id=@item.Key>Edycja</a>
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id=@item.Key>Szczegóły</a>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id=@item.Key>Usuń</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Laboratorium 3 - App/Views/Contact/PagedIndex.cshtml
@model PagingList<Contact>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Lista kontaktów</h1>
<a class="btn btn-primary" asp-area="" asp-controller="Contact" asp-action="Create">Dodaj Kontakt</a>
<a class="btn btn-primary" asp-area="" asp-controller="Contact" asp-action="CreateApi">Dodaj Kontakt API</a>
@if (Model.Data.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Data.First().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Data.First().Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Data.First().Priority)
                </th>              
                <th>
                    Akcje
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td class="@(item.Name.EndsWith("a")? "text-primary":"text-secondary")">  
                        @item.Name
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.Priority
                    </td>
                    <td>
                        <a class="btn btn-outline-success" asp-action="Update" asp-route-id="@item.Id">Edycja</a>
                        <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">Szczegóły</a>
                        <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                    </td>
                </tr>
            }
        </tbody>      
    </table>
}

<nav aria-label="Books page navigation">
    <ul class="pagination">
        @if (Model.IsPrevious)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="Contact"
                   asp-action="PagedIndex"
                   asp-route-page="@(Model.Page - 1)"
                   asp-route-size="@Model.Size">
                    Poprzednia
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link">Poprzednia</a>
            </li>
        }
        <li class="page-item disabled">
            <a class="page-link">@Model.Page</a>
        </li>
        @if (Model.IsNext)
        {
            <li class="page-item">
                <a class="page-link"
                   asp-controller="Contact"
                   asp-action="PagedIndex"
                   asp-route-page="@(Model.Page + 1)"
                   asp-route-size="@Model.Size">
                    Następna
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link">Następna</a>
            </li>
        }
    </ul>
</nav>

Laboratorium 3 - App/Views/Contact/Update.cshtml
@model Contact
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Edytuj kontakt</h1>
<form asp-controller="Contact" asp-action="Update" method="post">
    <input asp-for="Id"/>
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Numer telefonu</label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Birth">Data Urodzenia</label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Priority"></label>
        <select class="form-control" asp-for="Priority" asp-items="@Html.GetEnumSelectList<Priority>()"></select>
        <span class="text-danger" asp-validation-for="Priority"></span>
    </div>
    <div class="mb-3">
        <button class="btn btn-primary" type="submit"> Zapisz zmiany</button>
    </div>
</form>